C_LIST=[
	"Seçdiyiniz sosial media hesabı ilə çox çirkin fotoşəkil paylaş.", "Mesaj yazma" bölməsini telefonunuzdan açın, gözlərinizi bağlayın və mətni təsadüfi bir insana göndərin.",
	"Növbəti beş dəqiqə ərzində dediklərinizdən sonra," mi "deyəcəksiniz.,
	"Növbəti 5 dəqiqədə kiminsə heyvan olun.", "Oyunçulardan birinə instagram verin. Beş dəqiqə ərzində hər yerə baxmaq sərbəstdir.",
	"Serenadanı oyundan bir insana (bir kişi qız və bir qız oğlan) et", " növbəti 3 turda dialektlə danışın.",
	"Üç dəqiqə üçün uşaq olmaq iddia!","Sevdiyiniz şəkilinizi telefonunuza atın", "sevimli şəklinizi atın",
	"Şəxsi mesajlarınızı alın və onları qrupa atın","son çıxışınızı at",
	"Mən Psycho 20 bloknotda bir dəfə, fotoşəkilinizi yazın və son çıxışınızı teleqramda atın.", "Onun tərcümeyi-hal cümlə yazmaq + 18; o, 3 saat dayanacaq.!",
	"Qalereyanın bir hissəsini götürün və onu SS-dən atın", " qalereya 16. Şəkil çəkmək."İnstagram və ya teleqramda bilmədiyin bir kəsə məzəli anekdot deyil, danışın.",
	"Beşiyi de","bu gün haqqında qısa bir hekayə düşünün"."Mən səni sevirəm ki, qrup ən çox istəyirəm ki, əks cinsi yazın.",
	"Qalereya 16. Şəkil çəkmək.", "Qalereya 30. Şəkil çəkmək.", "Siz söhbət kimə SS insanların atmaq".,
	"Qrup iştirakçılarının siyahısına daxil olun və 7. Bir anlığa at! (Qrupda az və ya az aktiv olduqda, yuxarıdan saymağa davam et)",
	"Son dəfə danışdığınız insana" xoşbəxt cümə " yaz.(platforma əhəmiyyətli deyil)",
	"İndi özünüzü fotoşəkil çəkə və atlaya bilərsinizmi?""İştirakçılar" qrupuna daxil ol 11. (Ya Rəsulum!) insana de: "nə analar, nə də arılar doğum verir".",
	"Siz nifrət ünlü bir profil şəkil qoyun.", "Başınıza bir yumurta atın və bir şəkil atın",
	"Qrupda sevdiyin insanın şəklini çək, onun şəklini profildə çək", " balkonda və ya pəncərədə insanların necə eşitəcəkləri videoya yaydır və qrupa çıxart.",
	"Etiraf et: üzvləri oğurlamaq üçün neçə hesabınız var?", "Mən səni sevirəm ki, qrup beş şəhvətpərəst demək", " iki dəqiqə bir cücə kimi davranmaq.", "Seçdiyiniz heyvan təqlid.",
	"Seçdiyiniz obyekti yalamaq və bir qrupa şəkil atın.", "Sizin qrup həqiqətən yöndəmsiz şəkil göstər.",
	"Çirkin bir selfie edin və sosial media tətbiqlərindən birində yerləşdirin, 1,5 saat qalacaq.", "Bir qaşıq un yeyin və bir video almaq və ya bir qrup atmaq.",
	"Qurban bayramı münasibətilə təbrik edirəm ki, bilirdi heç kimə de","sevdiyin kimsə", "niyə səni sevdim, niyə səni sevdim, niyə sevdim, niyə səni sevdim, niyə sevdim, niyə səni sevdim, niyə sevdim, niyə səni sevdim, niyə sevdim səni sevdim, niyə sevdim?" heç bir izahat yoxdur. De: "Həqiqətən, sən mənim xoşuma gəlirsən". Cavab gəldikdə, onları bir qrupla paylaşın və biz güləcəyik".,
	"Teleqramda ən sıx məskunlaşan qrupu açın və De:"mənim adım duzlu xiyar ilə canistra!Səsi yaz və ən sıx məskunlaşan qrupa göndər."Dostun ona aşiq olduğunu yaxın dostuna söylə.", "Bir küp su içmək və bir şəkil çəkmək.",
	"Qarşı cinsin dostu, hansıyla ki, sən ən çox danışırsan" `mən səni çox sevirəm, hesab edirəm ki, mən vuruldum """yaz və öz reaksiyayla bizimlə paylaş",
	"Sizin ad Abdul<adınız> 1 saat olun. (məsələn, əgər sən berk deyirsən, Bunu Əbdülberkom et)", İnstagram-da"dm qutusunu ("mesajlar" bölməsini) götür və onu qrupa atın.",
	"Bilmədiyin bir kəsə de və Söhbətə başlayın:"əgər sevgimizin suya düşəcəyini bilsəydim, balıq olardım".,
	"Qrupu ilə ən komik fotoşəkilinizi paylaşın.""İştirakçılar" qrupuna daxil ol 11. İnsana de: "nə analar, nə də arı var?"və cavabınızı Qrupla paylaşın.",
	"Bilmədiyin bir şəxsə mesaj yaz, sonra da öz cavabını Qrupla bölüş", bu məlumat xüsusi tezlikdə göndərildi. Ağılsızların yaddaşının itirilməsi və gicgahlarda qısa müddətli korluq pediklərdə ani təbəssümə səbəb olur!`\"",
	"@yaz, ilk insanı xatırla və səni sevdiyimi yaz."Bilmədiyin birisini yaz," məncə, sənə aşiq oldum".",
	"Teleqram Haqqında"bölməsində"atanızın şahzadəsi" yaz, bir saat dayansın.", "Kimsə yüksək səslə öpmək və qeyd",
	"Son nitqinizi SS teleqramına at.", "Xoşbəxt mesaj" qrupdan hər hansı birinin Google/Fərmanı/İnstagram-da axtarış tarixini soruşun".,
	"Qalereyanın altındakı 7. Öz fotoşəkilini göndər",
	"Növbəti üç turda dialekt danışmaq. Müxtəlif dialekt bir kəmər / zar varsa, 6 ən uyğun olan oyunçu, sizə əzab verəcək.",
	"Acı tomat pastası (və ya bir şey) üç yemek kaşığı yeyin və bir video almaq və ya bir qrup atmaq.",
	"Ola bilsin ki, sən istəyəcəksən ki, kimdəsə oyunda 5 dəqiqə ərzində ev heyvanı olsun.", "Zəmini yalamaq və foto/videolarınızı qrupa atın",
	"Sosial media hesablarından birinin ən uyğun oyunçuya 6 və ya 5 dəqiqə vermək üçün komanda/zar istifadə edin.",
	"Üç dəqiqə ünlü təqlid.", "Kimsə təqlid rəssam guesses qədər rəssam təqlid",
	"Qrupun düşündüyü mövzuda səkkiz sətir və iki şeir yaz.",
	"(Birgə qərar " zar " komanda 1 yaxın oyunçu /öpücük qəbul edilə bilməz, əgər) bir səs verilməsi, oyun insanların ümumi qərarı ilə bir qrup kimsə Kiss.",
	"5 dəqiqə ərzində oyunda bir insanın köləsi olun.", "Bir süpürgə və ya Mop ilə rəqs və video atmaq",
	"Həqiqi məhəbbətin kim olduğunu elan et", "əlifbanı başdan sona qədər oxuyun, ağzını hərəkət etmədən, oxuduğunuz zaman video yay", " indi başınıza gələn ilk sözü söyləyin.",
	"Oyun oyunçularından biri haqqında bir hekayə düşünün"," 15 saniyə üçün sondan əlifbanı oxuyun, oxuduğunuz zaman səs verin","bir İt kimi büküldüyünüz zaman səs verin".,
	"Mahnını başdan sona qədər oxu, səsini çıxar", " görüşdüyün ən pis və ən yaxşı insana izah et.",
	"Qarşı cinsi bir insan kimi bir dəqiqə gedin."Sevgilinizə heç göndərə biləcəyiniz ən pis mesajı göndər."Oyunda iştirak edən hər bir şəxs haqqında bildiyin gülməli bir şey danışın.",
	"Məşhur restoranlardan birinə zəng edin və onların menyusunu tanıyana qədər zarafat edin. Dekan, bilmirəm.", "Köhnə mahnı kilidini açmaq və onun təqlid, onun oxumaq üçün cəhd, səs tələffüz", " 1 tur ərzində başqa bir dildə danışmaq.",
	"Köhnəni yaz və onu unuta bilməyəcəyinizi söylə.", "Siz"sözünü eşitdiyiniz zaman iki turda bir quş kimi səs verin.",
	"Telefonunuzda bütün brauzer tarixini göstər.", "Siz oda kimsə onu almaq üçün gedir kimi paltarları yoxlayın."
]

D_LIST = [
	"Telefonunuzda son dəfə nə çağırdınız?"Əgər kimsə sizin qız / sevgilinizlə ayrılmaq üçün bir milyon təklif etsə, bunu edərdiniz?",
	"Bu qrupda kimləri ən az sevirsiniz və niyə?"Sən nə vaxtsa sinifdə bərkdən qışqırmısan?",
	"Sən nə vaxtsa sinifdə bərkdən qışqırmısan?"Sən nə vaxtsa poldan nəsə götürüb yeyibsən?",
	"Əgər sən bir dəfə əks cins kimi oyansan, sən birinci nə edəcəksən?",
	"Sən nə vaxtsa hovuzda yazmısan?", "Sən nə vaxtsa liftdə qaz buraxmısan?",
	"Tualetdə oturduğunuz zaman ağla nə gəlir?", "Siz qaldırılmış bir xəyali dost idi?",
	"Ən pis vərdişiniz nədir?", "Burunda eşələnmək edə bilərəmmi?", "Vanna otağı oxumaq olar?",
	"Sən nə vaxtsa özünə yazmısan?", "Cəmiyyətdə ən utanc verici bir anınız nə idi?"Sən nə vaxtsa güzgüdə özünlə danışmısan?",
	"İnternetdə hekayənizi hər kəs görsəydi, nə xəcalət çəkərdiniz?", "Siz yuxu danışmaq olar?",
	"Gizli məhəbbətiniz kimdir?", "Mənim haqqında nə sevmirsiniz?"İndi nə rəng paltarları geyinirsən?",
	"Son mesajınız nə idi?"Əgər yanan binadan insanları xilas etsəydiniz və bu qrupdan bir insanı tərk etməli olsaydınız, kim olardı?",
	"Necə tez-tez paltarları yuyarsan?"Əgər qulaq kükürdünü sınamışdınız?",
	"Əgər farted və başqa kimsə ittiham mi?"Əgər sizin tər cəhd mi?",
	"Bu otaqda kim bu gün üçün ən pis adam olacaq? Niyə?",
	"Əgər yenidən doğulsaydın, hansı əsrdə doğulmaq istəyirsən?"Əgər söylədiyiniz və ya etdiyiniz şeyi silmək üçün vaxtında geri dönə bilsəydiniz, hansı il olardı?",
	"Sevgiliniz və ya qızınız bir dəfə sizi qarışdırdı?", "Əgər birdən-birə görünməz olsaydı nə edərdiniz?",
	"Banyoda qaldığınız ən uzun vaxt nədir və niyə belə uzun müddət qaldınız?"Mənə heç gördüyüm ən qəribə yuxu haqqında danışın.",
	"Sən qəlbində yazırsan?", "Siz hələ nə ən Uşaq şey nədir?", "Hansı Uşaq filmini təkrar-təkrar izləyə bilərsiniz?",
	"Ayağınızın pis qoxusu varmı?", "Siz gülünc ləqəb var?", "Telefonunuzda ən çox vaxtınızı hansı tətbiqdə sərf edirsiniz?",
	"Bir oturuşda yediyiniz ən böyük yemək nədir?", "Bir rəqs edirsiniz?", "Sən qaranlıqdan qorxursan?",
	"Bütün gün evdə olsaydı nə edərdiniz?"Gündə neçə öz-özünə işləyən çəkirsiniz?"Son dəfə dişlərinizi fırçaladığınız zaman?",
	"Sevdiyiniz pijama necə görünür?", "Əgər yerdən bir şey yeyilmiş mi?"Nə etməli olmadığın bir şey etdiyiniz zaman tutuldun?",
	"Bədəninizin hansı hissəsini sevirsiniz, hansı hissəni nifrət edirsiniz?", "Siz heç biti var?",
	"Əgər sizin şalvar biçmək mi?", "Siz boşqab yalama edirsiniz?", "Heç kim sənin haqqında bir şey bilmir?",
	"Sən nə vaxtsa öz boşqabını yandırıbsan?"Dirsək yalama edə bilərəmmi?"Burada hər kəsin yanan binadan qurtarmağa çalışırsan və kimsə tərk etməlisən, kimdən ayrılacaqsan?",
	"Telefon zəng etdiyiniz son şey nə idi?", "Sizin telefon app aradan qaldırılması idi, əgər siz silindi nə olardı?"Əlaqələrinizdə ən böyük qorxunuz nədir?",
	"Otaqda hər bir şəxs haqqında bir müsbət və bir mənfi şey söyləyin.", "Siz kimi deyil ki, pis vərdişləri var?",
	"Həyatınızda heç etdiyiniz ən çılpaq şey nədir?"Əgər adada üç gün sıxışmış olsaydınız, bu qrupdan kim seçərdiniz?",
	"Bu otaqda ən zəhlətökən adam kimdir?"Əgər bu qrupdan birinə evlənmək məcburiyyətində olsaydınız, kim olardı?", "Sizin ən uzun əlaqələr nə qədər davam etdi?",
	"Əgər ünlü sənə İnstagram' da tabe olsaydı, bu məşhurluğun kim olmasını istərdin?", "Əgər İnstagram' dakı Beşləri aradan qaldırmaq məcburiyyətində olsaydınız, kimdən çıxardınız?",
	"Neçə uşaq sahibi olmaq istəyirsən?", "Sizin xəyalları insan təsvir.", "Messi və ya Ronaldo?","Təslim olmaq və ya Fıfa?",
	"İlk işiniz nə idi?"Universitet qarşısında ən böyük qorxu nədir?"Ən yaxşı dostunuzun sənin kimi eyni kollecə daxil olmasını istəyirsinizmi?",
	"İndiki sevgilinizin və ya qızınızın eyni kollecdə olmasını istəyirsinizmi?", "Sizin xəyalları iş və nə?",
	"Siz dərs uğursuz mi?", "Siz heç bir hilekarlık var?", "Əgər sinif yuxuda mi?"Kim heç vaxt sinifdə yanınızda oturmaq istəmirsiniz?",
	"Sən nə vaxtsa dərslərə gecikmisən?", "Siz heç müəllim qarşısında nə ən utandırıcı nədir?"Sən nə vaxtsa saqqızı masanın altına atmısan?",
	"Əgər məktəbdə mübahisə etdiniz mi?", "Nə heç imtahan qəbul etdiyiniz ən pis bal idi?"Sinifdə yuxuya düşdünüzmü?"Səni nə vaxtsa yaxalayıblar?",
	"Əgər sən görünməz olsaydın, hansı dərsə gedərdin?", "Ən pis qrup nədir?", "Bu qrupda ən çox sirləri saxlamağa çətinlik çəkən kimdir?",
	"Söylədiyin son yalan nə idi?", "Siz idman edirsiniz?"Həyatınızın qalan hissəsi üçün yalnız bir materialı geyə bilərsənsə, materialı nə rəng olacaq?",
	"Sizcə, Türkiyənin təhsil sisteminə hansı ən vacib dəyişikliyi etmək lazımdır?", "Siz qaranlıq/yükseklik qorxuruq?",
	"1-dan 10-a qədər öz xarici görünüşünüzü hesaba qoyun:)", " nə vaxtsa nə etdiklərinizdən ən dekriminallaşdırılmış idi?"Əgər indi sənə təklif gəlsəydi, bu, sənin xoşuna gəlməyən kimsə idi və bu, sonuncu təklif olardı, razılaşardın?",
	"Cari əhval-ruhiyyənizə (fəaliyyət film/drama/elm fantastika/romantik komediya/tərcümeyi-hal/bədii) baxaraq hansı filmə baxırsınız?",
	"Ən məğlub hiss etdiyiniz an nə idi?"Əgər gələcəkdə uşaqlarınız varsa, nə ad vermək istəyirsən?",
	"Bir unicorn və ya bir dragon olmasını istəyirsinizmi?","Nə qədər lover idi?", "Həyatda unutmadınız kimsə varmı?",
	"Sevdiyiniz mahnı?"Nə etməli olmadığın bir şey etdiyiniz zaman tutuldun?", "Sevimli rəssam Kimdir?",
	"Sənin diqqətini ilk dəfə əks cinsə nə cəlb edib?", "Bu il həyatınızda nəyi dəyişdirmək lazım olduğunu düşünürsən?",
	"Kiminsə telefon gördüm ki, ən qəribə şey nədir?", "Həqiqətən superheroes mövcud olsaydı dünya nə olardı?",
	"Həyat sizə ən vacib dərs nədir?", "Bizim mədəniyyətimizdə ən çox nə xoşunuza gəlir?", "Ailənizin tətbiq etdiyi ən qəribə ənənə nədir?",
	"Ailənizdən başqa, həyatınıza ən böyük təsir göstərən kimdir?", "Bir kişi/qadın olmaq üçün ən pis və ən yaxşı nədir?",
	"Əgər beyninizi robotun içərisinə qoysaydınız və əbədi yaşayırsınızsa, bunu edərdiniz?"Kim heç evində qəbul etdiyiniz ən pis qonaq idi və nə oldu?",
	"Siz insanların soruşduqları şeylərdən yoruldunuz?", "Ən qəribə qorxu nədir?","Sevimli TV nə?", "Əgər müzakirə etdiyiniz ən gülməli müzakirə nədir?",
	"Son yalan nədir?"Kimsə ilə görüşərkən nə vaxtsa etdiyiniz ən utanc verici nə idi?",
	"Sən nə vaxtsa təsadüfən öz maşınında kimisə vurmusan (əgər varsa)?",
	"Sənin fikrincə, sənin xoşuna gələn, ancaq heç cür aça bilməyən kimsə olubmu?", "Ən qəribə ləqəbiniz nədir?",
	"Fiziki cəhətdən ən ağrılı təcrübənizə nə oldu?", "Hansı körpülər sənə təsəlli verdilər?",
	"Nə heç İctimai Nəqliyyat nə ən dəli idi?"Şüşə içərisindən gin çıxsaydı, üç istəkləriniz nə olardı?"Əgər sən dünyada kimisə Türkiyənin prezidenti edə bilsəydin, bu, kim olardı?",
	"Nə heç başqasına dedi ki, ən qəddar idi?"Kimsə öpdüyünüz zaman heç pis hiss etdinizmi?"Nəticənin olmayacağını bilsən, nə etmək istərdin?",
	"Ən dəlisov nədir, nə vaxtsa güzgünün qarşısında nə etmisən?"Nə heç başqasına danışıb ki, ən əhəmiyyətli idi?",
	"Dostlarınızla nə etməyi sevirsiniz, amma qızınızın qarşısında heç vaxt bunu etməyəcəksiniz?"Bu həyatda ən çox kimə qısqanırsan?",
	"Sevdiyiniz pijama necə görünür?"Sən nə vaxtsa görüşməkdən qaçmaq üçün xəstə kimi davranmısan?"Görüşdüyünüz ən yaşlı adam kimdir?",
	"Gündə neçə Selfie edirsiniz?"Mən hər şeyi sevgi üçün edəcəyəm, amma mənim üçün nə deyirsən "bu"?"Həftədə neçə dəfə eyni şalvarını geyirsiniz?",
	"Əgər bu gün şansınız olsaydı, məktəb sevgisi ilə görüşərdiniz?", "Bədəninizin hansı hissələrindən qıdıqlanırsınız?",
	"Siz müxtəlif xurafat var? Onlar nə varsa?", "Hansı film sevgini etiraf etməkdən utanırsınız?"Şəxsi gigiyena üçün ən utanc verici vərdişiniz nədir?", "Son dəfə nə vaxt və nə üçün üzr istəyirsən?", "Şifahi dastanlar haqqında nə düşünürsünüz?",
	"Sizin yöndəmsiz qoxuların böyük bir hissəsi haradan alınır?"Sən nə vaxtsa öz qızından danışmağı düşünürdün?"Əgər kimsə ilə onun boyfriend cheated mi?", "Boksçu, yoxsa qısa tuman?", "Əgər hovuz və ya dəniz yazılı mi?"Saçınızı böyütmək barədə düşünsəniz, nə qədər uzanacaqsınız?"Heç kimin bilməyəcəyi bir zəmanət olsaydı, kimləri öldürmək istərdiniz?"Başqası üçün nə qədər ucuz hədiyyə aldın?",
	"Zamanınızın çox hissəsini ən çox hansı tətbiqdə keçirirsiniz?"Avtobusda nə etdiyiniz ən qəribə şey nədir?", "Siz heç ictimai çılpaq idi?"Gündə neçə qeybət edirsiniz?"Neçə yaş olardı ki, onunla görüşmək istədiyin ən gənc adam olsun?"İctimaiyyətdə olanda burun içində hıçqırırdınız?",
	"Yaşınız haqqında yalan danışırdınız?", "Sizin telefon app aradan qaldırılması olsaydı nə olardı?",
	"Heç gec gecə etdiyiniz ən utandırıcı şey nədir?", "Necə uzun siz duş olmadan bütün artıq var?"Sən nə vaxtsa saxta sənədlərdən istifadə etmisən?"Qırmızı xalça üzərində gəzmək istədiyiniz məşhur ad kimdir?", "Sizin gizli sevgi kimdir?"
]
