
C_LİST=[
	"Seçtiğiniz bir sosyal medya hesabınızdan çok çirkin bir fotoğrafınızı paylaşın.","Mesaj yazma bölümünüzü telefonunuzdan açın gözlerinizi kapatın ve rasgele bir kişiye körü körüne bir metin gönderin.",
	"Önümüzdeki 5 dakika boyunca söylediğin her şeyden sonra “mee” diyeceksin",
	"Önümüzdeki 5 dakika içinde birinin hayvanı olun.","İnstagramını oyunculardan birine ver. 5 dk boyunca her yere bakmak serbest.",
	"Oyundan bir kişiye serenat yap (kız ise erkeğe, erkek ise kıza)","Sonraki 3 tur boyunca şiveyle konuş.",
	"3 dakika boyunca bebek taklidi yap!","Telefonunda ki en sevmediğin fotoğrafını at","En beğendiğin fotoğrafını at",
	"Whatsapp’da 2 konuşmanı at","Özel mesajlarını ssi al ve gruba at","Whatsapp’da son konuşmanı at",
	"Bir deftere 20 kez ben çatlağım yaz ve resmini at","Telegramda son konuşmanı ss at.","Biyografine +18 bir cümle yaz; 3 Saat duracak.!",
	"Galerinin bir kısmını ss alıp at","Galerindeki 16. Fotoğrafı at.","Instagram yada telegramdan tanımadığın birine komik olmayan bir fıkra anlat.",
	"Ninni Söyleyerek Ses At","Bugununle ilgili kısa bir hikaye uydur.","Grupta ki en çok hoşuna giden karşı cinse seni seviyorum diye mesaj at.",
	"Galerindeki 16. Fotoğrafı at.","Galerindeki 30. Fotoğrafı at.","Whatsapp’da konuşduğun kişilerin ss ini at",
	"Grubun üye listesine gir ve 7. kişiye anlık at. (Grup daha az kişiyse ya da aktif sayısı azsa üstten saymaya devam et)",
	"En son konuştuğun kişiye \"Hayırlı Cumalar\" diye mesaj at.(platform farketmez)",
	"Şuan ki halini fotoğraf çekip  atar mısın?","Grupta üyeler kısmına gir 11. kişiye \"Analar neler doğuruyor bee\" diye ses at ve cevabını grupla paylaş.",
	"Profil fotoğrafına nefret ettiğin bir ünlünün resmini koy.","Kafanda yumurta kır ve fotosunu at",
	"Gruptan sevdiğin bir kişinin fotoğrafını profil resmi yap","Balkona veya pencereye cık dısardakılerın duyacagı sekılde sarkı soyle videoya al gruba at.",
	"İtiraf et: üye çalmak için kaç hesabın var?","Gruptaki 5 abazaya seni seviyorum de","İki dakika tavuk gibi davran.","Seçtiğiniz bir hayvanı taklit edin.",
	"Seçtiğin bir nesneyi yalayın ve gruba fotosunu atın.","Gruba gerçekten utanç verici bir fotoğrafını göster.",
	"Çirkin bir selfie çek ve sosyal medya uygulamalarından birinde yayınla 1.5 saat kalacak.","Bir kaşık un ye ve video ya al gruba at",
	"Hiç tanımadığın birine Kurban Bayramınızı kutlarım deyin","Sevdiğin bir kişiye \"`ben seni neden sevdim niçin sevdim niye sevdim bunların bi izahı yok gördün işte sevdim. Yaw sahi ben seni nidennn sevdim `\" de. Cevap geldiğinde grupla paylaş biz de gülelim",
	"Telegram'daki en kalabalık grubu aç ve \"`Benim adım turşu bidonu!`\" diyerek ses kaydedip en kalabalık gruba gönder.","Hemcinsin olan yakın bir arkadaşına ona aşık olduğunu söyle.","Sürahiden su iç ve fotoğraf at.",
	"En çok konuştuğun karşı cinsten arkadaşına \" `Seni çok seviyorum galiba aşık oldum`\" yaz ve tepkisini bizimle paylaş",
	"İsmini 1 saatliğine Abdül<ismin> yap. (örneğin adın Berk ise AbdülBerk yap)","İnstagram'da dm kutunu (mesajlar bölümü) ss al gruba at.",
	"Tanımadığın birisine şu cümleyi atıp sohbet başlat: \"`Aşkımızın suya düşeceğini bilseydim , balık olurdum`\"",
	"En komik fotoğrafını grupla paylaş.","Grupta üyeler kısmına gir 11. kişiye \"`Analar neler doğuruyor bee`\" diye ses at ve cevabını grupla paylaş.",
	"Tanımadığın birine şu mesajı at sonra cevabını grupla paylaş ➡️\n  \"`Bu mesaj özel bir frekansla gönderilmiştir. Zekilerde hafıza kaybı, aptallarda kısa sureli körlük ibnelerde de bir anlık gülümseme yapar!`\"",
	"@ yaz çıkan ilk kişiyi etiketle ve seni seviyorum yaz.","Tanımadığın birine \" `sanırım sana aşık oldum`\" diye mesaj at.",
	"Telegram hakkında kısmına \"`Babasının Prensesi`\" yaz 1 saat boyunca dursun.","Birine Sesli Öpücük At Ve Etiketle",
	"Telegramda son konuşmanı ss at.","🎀 ŞANSLI MESAJ🎊 Grupdan İstediğin Birinin Google/Youtube/İnstagram Arama Geçmişini İste",
	"Galerinin En Alttan 7. Fotosunu gönder",
	"Sonraki 3 tur boyunca şiveyle konuş. Farklı şivelere kayış olursa /zar Komutunu kullanarak 6 ya en cok yaklaşan oyuncu sana ceza verecek",
	"Üç çorba kaşığı acı salça (veya buna benzer bir şey) ye ve video ya al gruba at",
	"5 dakika boyunca oyundaki birinin evcil hayvanı olmasını isteyebilirsin.","Yeri yala Ve fotoğraf/videosunu gruba at",
	"/zar Komutunu kullanarak 6 ya en cok yaklaşan oyuncuya sosyal medya hesaplarından birini 5dk ver",
	"3 dakika boyunca bir ünlüyü taklit et.", "Birisi taklit edilen sanatçıyı tahmin edene kadar bir sanatçıyı taklit et",
	"Grubun ortaya koyduğu bir konu etrafında sekiz satır ve iki mısralık bir şiir yaz",
	"Oyundaki kişilerin ortak kararıyla gruptan birini öp ses atarak (ortak karar verilemezse /zar komutundan 1 e en yakın oyuncuyu öp).",
	"5 dakika boyunca oyundaki bir kişinin kölesi ol.", "Bir süpürgeyle veya paspas ile dans et ve videosunu at",
	"Gerçek aşkının kim olduğunu ilan et","Ağzını hareket ettirmeden baştan sona alfabeyi oku okurken video at", "Aklına gelen ilk kelimeyi hemen söyle.",
	"Oyundaki oyunculardan biri hakkında hikaye uydur", "15 saniye içerisinde sondan başa doğru alfabeyi oku okurken ses at", "Bir köpek gibi havla havlarken ses at",
	"Bir şarkıyı baştan sona söyle söylerken ses at","Çıktığın en kötü ve en iyi kişiyi açıkla.",
	"Bir dakika boyunca karşı cinsten biri gibi yürü.","Sevgiline atıp atabileceğin en acımasız mesajı gönder.","Oyunda yer alan her kişi hakkında bildiğin komik bir şey anlat.",
	"Ünlü restoranlardan birini ara ve menülerini öğrenirken dalga geç.","Eski bir şarkıyı aç ve onu taklit ederek söylemeye çalış söylerken ses at","1 tur boyunca farklı bir dilde konuş.",
	"Eski sevgiline mesaj at ve onu unutamadığını söyle.","2 tur boyunca “sen” kelimesini duyunca kuş gibi ses çıkart.",
	"Telefondaki tarayıcı geçmişini herkese göster.","Odadan birisi için satın alacakmış gibi iç çamaşırı araştırması yap."
]

D_LİST = [
	"Telefonunda en son aradığın şey neydi?","Birisi kız arkadaşın / erkek arkadaşından ayrılmak için sana 1 milyon tl önerseydi, yapar mıydın?",
	"Bu grupda en az kimi seviyorsun ve neden?","Hiç sınıfta yüksek sesle geğirdin mi?",
	"Hiç sınıfta yüksek sesle geğirdin mi?","Yerden bir şeyi alıp hiç yedin mi?",
	"Bir gün karşı cins olarak uyanırsan, ilk yapacağın şey nedir?",
	"Hiç havuzda işedin mi?","Asansörde hiç gaz kaçırdın mı?",
	"Tuvalette otururken aklınıza gelen şeyler nelerdir?","Büyüyen hayali bir arkadaşınız var mıydı?",
	"En kötü alışkanlığınız nedir?","Burnunu karıştırır mısın?","Banyoda şarkı söyler misin?",
	"Hiç üzerine işedin mi?","Toplumda en utanç verici anınız neydi?","Aynada kendinle hiç konuştun mu?",
	"Web geçmişinizi, birileri görürse utanacağınız şey ne olurdu?","Uykunda konuşur musun?",
	"Gizli aşkın kim?","Benim hakkımda neyi sevmiyorsun?","Şu an ne renk iç çamaşır giyiyorsun?",
	"Son attığın mesaj neydi?","İnsanları yanan bir binadan kurtarıyor olsaydınız ve bir kişiyi bu grupdan geride bırakmak zorunda kalırsanız, kim olurdu?",
	"İç çamaşırlarını ne sıklıkla yıkıyorsun?","Hiç kulak kiri tattın mı?",
	"Hiç osurup başka birini suçladın mı?","Hiç terinin tadına baktın mı?",
	"Bu odadaki kim bugüne kadarki en kötü insan olurdu? Neden?",
	"Yeniden doğmuş olsaydın, hangi yüz yılda doğmak isterdin?","Söylediğiniz veya yaptığınız bir şeyi silmek için zamanda geriye gidebilseydiniz, bu hangi yıl olurdu?",
	"Erkek arkadaşın veya kız arkadaşın seni hiç utandırdı mı?","Birdenbire görünmez olsaydın ne yapardın?",
	"Banyoda kaldığınız en uzun süre nedir ve neden bu kadar uzun süre kaldınız?","Şimdiye kadar gördüğüm en garip rüyayı anlat.",
	"Duşta işiyor musun?","Hala yaptığın en çocukça şey nedir?","Hangi çocuk filmini tekrar tekrar izleyebilirsin?",
	"Ayak kokunuz kötü mü?","Saçma takma adların var mı?","Telefonunuzda hangi uygulamada en çok zaman harcıyorsunuz?",
	"Tek bir oturuşta yediğin en çok yemek ne?","Tek başınayken dans ediyor musun?","Karanlıktan korkar mısın?",
	"Bütün gün evdeysen ne yapardın?","Günde kaç öz çekim yapıyorsunuz?","En son ne zaman dişlerini fırçaladın?",
	"En sevdiğin pijamalar neye benziyor?","Hiç yerden bir şey yedin mi?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?",
	"Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?","Hiç bitlendin mi?",
	"Pantolonunu hiç kestin mi?","Tabağını yalıyor musun?","Kimsenin senin hakkında bilmediği bir şey nedir?",
	"Hiç tabağını yaladın mı?","Dirseğini yalayabilir misin?","Eğer buradaki herkesi yanan bir binadan kurtarmaya çalışıyor olsaydın ve birini geride bırakmak zorunda kalırsan, kimi geride bırakırdın?",
	"Telefonda aradığın son şey neydi?","Bir uygulamayı telefonunuzdan silmek zorunda kalsanız hangisini silerdiniz?","Bir ilişkideki en büyük korkun nedir?",
	"Odanın her bir kişi hakkında bir tane olumlu, bir tane olumsuz şey söyleyin.","Sevmediğin kötü huyun var mı?",
	"Hayatında yaptığın en çılgın şey nedir?","Üç gün boyunca bir adada mahsur kalmış olsaydınız, bu grupdan kimleri seçerdiniz?",
	"Bu odadaki en sinir bozucu kişi kim?","Bu grupdan biriyle evlenmek zorunda kalsan kim olurdu?","En uzun ilişkiniz ne kadar sürdü?",
	"Bir ünlü Instagram’da seni takip etseydi bu ünlünün kim olmasını isterdin?","Instagram’da 5 kişiyi silmek zorunda olsan kimleri silerdin?",
	"Kaç çocuk sahibi olmak istersin?","Hayallerinizdeki kişiyi tarif edin.","Messi mi Ronaldo mu?","Pes mi Fifa mı?",
	"İlk işin neydi?","Üniversite hakkındaki en büyük korkun nedir?","En iyi arkadaşının seninle aynı üniversiteye gitmesini ister misin?",
	"Mevcut erkek arkadaşının ya da kız arkadaşının seninle aynı üniversiteye gitmesini ister misin?","Hayalindeki iş ne?",
	"Hiç bir dersten başarısız oldun mu?","Hiç kopya çektin mi?","Hiç sınıfta uyudun mu?","Sınıfta asla yanında oturmak istemeyeceğin kim?",
	"Derse hiç geç kaldın mı?","Bir öğretmenin önünde yaptığın en utanç verici şey nedir?","Hiç masanın altına sakız attın mı?",
	"Hiç okulda kavga ettin mi?","Bir sınavdan aldığın en kötü puan neydi?","Sınıfta hiç uyuya kaldın mı?","Hiç gözaltına alındın mı?",
	"Eğer görünmez olsaydın hangi derse gizlice girerdin?","En kötü grup hangisidir?","Bu grupdaki sır tutma  konusunda en çok zorlanan kişi kimdir?",
	"Söylediğin en son yalan neydi?","Spor yapar mısın?","Hayatının geri kalanında sadece bir kıyafet giyebilseydin, bu kıyafetin hangi renk olurdu?",
	"Sizce Türkiye’nin eğitim sisteminde yapılması gereken en önemli değişiklik nedir?","Karanlıktan/yükseklikten korkar mısın?",
	"Kendi görünuşünü 1 ile 10 arasında puanla :)","Yaptıgın en yasadışı şey neydi?","Şimdi sana bir evlenme teklifi gelse ve sevmediğin biri olsa, ve bu sana son gelecek evlilik teklifi olsa kabul edermiydin?",
	"Şu anki ruh haline bakarak ne tür film izlersin (aksiyon/dram/bilim kurgu/romantik komedi/biyografi/fantastik)",
	"Kendini en ezik hissettiğin an hangisiydi ?","ilerde çocuğun olursa ne isim koymak istersin?",
	"Unicorun mu olmasını isterdin ejderhan mı?","Kaç sevgilin oldu?","Hayatta unutmadığın biri var mı?",
	"en sevdiğin şarkı?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?","En sevdiğin sanatçı kim?",
	"karşı cinste ilk dikkatini çeken ne?","bu yıl hayatında neyi değişmeyi uygun görüyorsun?",
	"Birinin telefonunda gördüğün en tuhaf şey nedir?","Süper kahramanlar gerçekten var olsaydı Dünya nasıl bir yer olurdu?",
	"Hayatın size öğrettiği en önemli ders nedir?","Kültürümüzün en çok sevdiğiniz yanı nedir?","Ailenizin uyguladığı en tuhaf gelenek nedir?",
	"Aileniz dışında, yaşamınız üzerinde en büyük etkisi olan kişi kimdir?","Kadın/Erkek olmanın en kötü ve en iyi yanı nedir?",
	"Beynini bir robota yerleştirebilir ve sonsuza kadar bu şekilde yaşayabilsedin,bunu yapar mıydın?","Evinizde ağırladığın en kötü misafir kimdi ve ne oldu?",
	"İnsanların size ne sormasından bıktınız?","En tuhaf korkunuz nedir?","En sevdiğiniz TV programı hangisidir?","Girdiğiniz en saçma tartışma nedir?",
	"En son söylediğin yalan nedir?", "Biriyle çıkarken yaptığın en utanç verici şey neydi?",
	"Hiç arabanla (varsa) yanlışlıkla bir şeye birine çarptın mı?",
	"Hoşuna gittiğini düşündüğün ama bir türlü açılamadığın biri oldu mu?","En tuhaf takma adın nedir?",
	"Fiziksel olarak sana en acı veren deneyimin ne oldu?","Hangi köprüleri yakmak seni rahatlattı?",
	"Toplu taşıma araçlarında yaptığın en çılgınca şey neydi?","Şişeden bir cin çıksa üç dileğin ne olurdu?","Dünyadaki herhangi birini Türkiye’nin başkanı yapabilseydin bu kim olurdu?",
	"Şimdiye kadar bir başkasına söylediğin en acımasızca şey neydi?","Birini öperken kendini hiç kötü hissettin mi?","Hiçbir sonucu olmayacağını bilsen ne yapmak isterdin?",
	"Bir aynanın önünde yaptığın en çılgınca şey nedir?","Şimdiye kadar başkasına söylediğin en anlamlı şey neydi?",
	"Arkadaşlarınla yapmayı sevdiğin ama sevgilinin önünde asla yapmayacağın şey nedir?","Bu hayatta en çok kimi kıskanıyorsun?",
	"En sevdiğin pijamaların neye benziyor?","Bir buluşmadan kaçmak için hiç hasta numarası yaptın mı?","Çıktığın en yaşlı kişi kim?",
	"Günde kaç tane özçekim yaparsın?","Aşk için her şeyi yaparım ama “bunu” yapmam dediğin şey nedir?","Haftada kaç kez aynı pantolonu giyiyorsun?",
	"Bugün şansın olsa lise aşkınla çıkar mısın?","Vücudunun hangi bölümlerinden gıdıklanıyorsun?",
	"Çeşitli batıl inançların var mı? Varsa onlar neler?","Sevdiğini itiraf etmekten utandığın film hangisidir?","En utan verici kişisel bakım alışkanlığın nedir?","En son ne zaman ve ne için özür diledin?","Sözlü destanlar hakkında ne düşünüyorsun?",
	"Utanç verici kokularınızın çoğu nereden geliyor?","Hiç sevgilini anlatmayı düşündün mü?","Hiç sevgilini biriyle aldattın mı?","Boxer mı yoksa külot mu?","Hiç havuza veya denize işedin mi?","Saçlarını uzatmayı düşünsen ne kadar uzatırdın?","Kimsenin bilmeyeceği garanti olsa kimi öldürmek isterdin?","Başkası için aldığın en ucuz hediye nedir?",
	"Zamanının çoğunu en çok hangi uygulamada harcıyorsun?","Otobüste yaptığın en tuhaf şey nedir?","Hiç toplum içinde çıplak kaldın mı?","Günde ne kadar dedikodu yaparsın?","Çıkmak isteyeceğin en genç kişi kaç yaşında olurdu?","Hiç toplum içindeyken burnunu karıştırdın mı?",
	"Hiç yaşın hakkında yalan söyledin mi?","Telefonundan bir uygulamayı silmek zorunda olsan bu hangisi olurdu?",
	"Gece geç saatte yaptığın en utanç verici şey nedir?","Duş almadan en uzun süre ne kadar durdun?","Hiç sahte kimlik kullandın mı?","Kırmızı halıda beraber yürümek istediğin ünlü isim kim?","Gizli aşkın kim?"
]
C_LIST=[
	"Seçdiyiniz sosial media hesabı ilə çox çirkin fotoşəkil paylaş.", "Mesaj yazma" bölməsini telefonunuzdan açın, gözlərinizi bağlayın və mətni təsadüfi bir insana göndərin.",
	"Növbəti beş dəqiqə ərzində dediklərinizdən sonra," mi "deyəcəksiniz.,
	"Növbəti 5 dəqiqədə kiminsə heyvan olun.", "Oyunçulardan birinə instagram verin. Beş dəqiqə ərzində hər yerə baxmaq sərbəstdir.",
	"Serenadanı oyundan bir insana (bir kişi qız və bir qız oğlan) et", " növbəti 3 turda dialektlə danışın.",
	"Üç dəqiqə üçün uşaq olmaq iddia!","Sevdiyiniz şəkilinizi telefonunuza atın", "sevimli şəklinizi atın",
	"Şəxsi mesajlarınızı alın və onları qrupa atın","son çıxışınızı at",
	"Mən Psycho 20 bloknotda bir dəfə, fotoşəkilinizi yazın və son çıxışınızı teleqramda atın.", "Onun tərcümeyi-hal cümlə yazmaq + 18; o, 3 saat dayanacaq.!",
	"Qalereyanın bir hissəsini götürün və onu SS-dən atın", " qalereya 16. Şəkil çəkmək."İnstagram və ya teleqramda bilmədiyin bir kəsə məzəli anekdot deyil, danışın.",
	"Beşiyi de","bu gün haqqında qısa bir hekayə düşünün"."Mən səni sevirəm ki, qrup ən çox istəyirəm ki, əks cinsi yazın.",
	"Qalereya 16. Şəkil çəkmək.", "Qalereya 30. Şəkil çəkmək.", "Siz söhbət kimə SS insanların atmaq".,
	"Qrup iştirakçılarının siyahısına daxil olun və 7. Bir anlığa at! (Qrupda az və ya az aktiv olduqda, yuxarıdan saymağa davam et)",
	"Son dəfə danışdığınız insana" xoşbəxt cümə " yaz.(platforma əhəmiyyətli deyil)",
	"İndi özünüzü fotoşəkil çəkə və atlaya bilərsinizmi?""İştirakçılar" qrupuna daxil ol 11. (Ya Rəsulum!) insana de: "nə analar, nə də arılar doğum verir".",
	"Siz nifrət ünlü bir profil şəkil qoyun.", "Başınıza bir yumurta atın və bir şəkil atın",
	"Qrupda sevdiyin insanın şəklini çək, onun şəklini profildə çək", " balkonda və ya pəncərədə insanların necə eşitəcəkləri videoya yaydır və qrupa çıxart.",
	"Etiraf et: üzvləri oğurlamaq üçün neçə hesabınız var?", "Mən səni sevirəm ki, qrup beş şəhvətpərəst demək", " iki dəqiqə bir cücə kimi davranmaq.", "Seçdiyiniz heyvan təqlid.",
	"Seçdiyiniz obyekti yalamaq və bir qrupa şəkil atın.", "Sizin qrup həqiqətən yöndəmsiz şəkil göstər.",
	"Çirkin bir selfie edin və sosial media tətbiqlərindən birində yerləşdirin, 1,5 saat qalacaq.", "Bir qaşıq un yeyin və bir video almaq və ya bir qrup atmaq.",
	"Qurban bayramı münasibətilə təbrik edirəm ki, bilirdi heç kimə de","sevdiyin kimsə", "niyə səni sevdim, niyə səni sevdim, niyə sevdim, niyə səni sevdim, niyə sevdim, niyə səni sevdim, niyə sevdim, niyə səni sevdim, niyə sevdim səni sevdim, niyə sevdim?" heç bir izahat yoxdur. De: "Həqiqətən, sən mənim xoşuma gəlirsən". Cavab gəldikdə, onları bir qrupla paylaşın və biz güləcəyik".,
	"Teleqramda ən sıx məskunlaşan qrupu açın və De:"mənim adım duzlu xiyar ilə canistra!Səsi yaz və ən sıx məskunlaşan qrupa göndər."Dostun ona aşiq olduğunu yaxın dostuna söylə.", "Bir küp su içmək və bir şəkil çəkmək.",
	"Qarşı cinsin dostu, hansıyla ki, sən ən çox danışırsan" `mən səni çox sevirəm, hesab edirəm ki, mən vuruldum """yaz və öz reaksiyayla bizimlə paylaş",
	"Sizin ad Abdul<adınız> 1 saat olun. (məsələn, əgər sən berk deyirsən, Bunu Əbdülberkom et)", İnstagram-da"dm qutusunu ("mesajlar" bölməsini) götür və onu qrupa atın.",
	"Bilmədiyin bir kəsə de və Söhbətə başlayın:"əgər sevgimizin suya düşəcəyini bilsəydim, balıq olardım".,
	"Qrupu ilə ən komik fotoşəkilinizi paylaşın.""İştirakçılar" qrupuna daxil ol 11. İnsana de: "nə analar, nə də arı var?"və cavabınızı Qrupla paylaşın.",
	"Bilmədiyin bir şəxsə mesaj yaz, sonra da öz cavabını Qrupla bölüş", bu məlumat xüsusi tezlikdə göndərildi. Ağılsızların yaddaşının itirilməsi və gicgahlarda qısa müddətli korluq pediklərdə ani təbəssümə səbəb olur!`\"",
	"@yaz, ilk insanı xatırla və səni sevdiyimi yaz."Bilmədiyin birisini yaz," məncə, sənə aşiq oldum".",
	"Teleqram Haqqında"bölməsində"atanızın şahzadəsi" yaz, bir saat dayansın.", "Kimsə yüksək səslə öpmək və qeyd",
	"Son nitqinizi SS teleqramına at.", "Xoşbəxt mesaj" qrupdan hər hansı birinin Google/Fərmanı/İnstagram-da axtarış tarixini soruşun".,
	"Qalereyanın altındakı 7. Öz fotoşəkilini göndər",
	"Növbəti üç turda dialekt danışmaq. Müxtəlif dialekt bir kəmər / zar varsa, 6 ən uyğun olan oyunçu, sizə əzab verəcək.",
	"Acı tomat pastası (və ya bir şey) üç yemek kaşığı yeyin və bir video almaq və ya bir qrup atmaq.",
	"Ola bilsin ki, sən istəyəcəksən ki, kimdəsə oyunda 5 dəqiqə ərzində ev heyvanı olsun.", "Zəmini yalamaq və foto/videolarınızı qrupa atın",
	"Sosial media hesablarından birinin ən uyğun oyunçuya 6 və ya 5 dəqiqə vermək üçün komanda/zar istifadə edin.",
	"Üç dəqiqə ünlü təqlid.", "Kimsə təqlid rəssam guesses qədər rəssam təqlid",
	"Qrupun düşündüyü mövzuda səkkiz sətir və iki şeir yaz.",
	"(Birgə qərar " zar " komanda 1 yaxın oyunçu /öpücük qəbul edilə bilməz, əgər) bir səs verilməsi, oyun insanların ümumi qərarı ilə bir qrup kimsə Kiss.",
	"5 dəqiqə ərzində oyunda bir insanın köləsi olun.", "Bir süpürgə və ya Mop ilə rəqs və video atmaq",
	"Həqiqi məhəbbətin kim olduğunu elan et", "əlifbanı başdan sona qədər oxuyun, ağzını hərəkət etmədən, oxuduğunuz zaman video yay", " indi başınıza gələn ilk sözü söyləyin.",
	"Oyun oyunçularından biri haqqında bir hekayə düşünün"," 15 saniyə üçün sondan əlifbanı oxuyun, oxuduğunuz zaman səs verin","bir İt kimi büküldüyünüz zaman səs verin".,
	"Mahnını başdan sona qədər oxu, səsini çıxar", " görüşdüyün ən pis və ən yaxşı insana izah et.",
	"Qarşı cinsi bir insan kimi bir dəqiqə gedin."Sevgilinizə heç göndərə biləcəyiniz ən pis mesajı göndər."Oyunda iştirak edən hər bir şəxs haqqında bildiyin gülməli bir şey danışın.",
	"Məşhur restoranlardan birinə zəng edin və onların menyusunu tanıyana qədər zarafat edin. Dekan, bilmirəm.", "Köhnə mahnı kilidini açmaq və onun təqlid, onun oxumaq üçün cəhd, səs tələffüz", " 1 tur ərzində başqa bir dildə danışmaq.",
	"Köhnəni yaz və onu unuta bilməyəcəyinizi söylə.", "Siz"sözünü eşitdiyiniz zaman iki turda bir quş kimi səs verin.",
	"Telefonunuzda bütün brauzer tarixini göstər.", "Siz oda kimsə onu almaq üçün gedir kimi paltarları yoxlayın."
]

D_LIST = [
	"Telefonunuzda son dəfə nə çağırdınız?"Əgər kimsə sizin qız / sevgilinizlə ayrılmaq üçün bir milyon təklif etsə, bunu edərdiniz?",
	"Bu qrupda kimləri ən az sevirsiniz və niyə?"Sən nə vaxtsa sinifdə bərkdən qışqırmısan?",
	"Sən nə vaxtsa sinifdə bərkdən qışqırmısan?"Sən nə vaxtsa poldan nəsə götürüb yeyibsən?",
	"Əgər sən bir dəfə əks cins kimi oyansan, sən birinci nə edəcəksən?",
	"Sən nə vaxtsa hovuzda yazmısan?", "Sən nə vaxtsa liftdə qaz buraxmısan?",
	"Tualetdə oturduğunuz zaman ağla nə gəlir?", "Siz qaldırılmış bir xəyali dost idi?",
	"Ən pis vərdişiniz nədir?", "Burunda eşələnmək edə bilərəmmi?", "Vanna otağı oxumaq olar?",
	"Sən nə vaxtsa özünə yazmısan?", "Cəmiyyətdə ən utanc verici bir anınız nə idi?"Sən nə vaxtsa güzgüdə özünlə danışmısan?",
	"İnternetdə hekayənizi hər kəs görsəydi, nə xəcalət çəkərdiniz?", "Siz yuxu danışmaq olar?",
	"Gizli məhəbbətiniz kimdir?", "Mənim haqqında nə sevmirsiniz?"İndi nə rəng paltarları geyinirsən?",
	"Son mesajınız nə idi?"Əgər yanan binadan insanları xilas etsəydiniz və bu qrupdan bir insanı tərk etməli olsaydınız, kim olardı?",
	"Necə tez-tez paltarları yuyarsan?"Əgər qulaq kükürdünü sınamışdınız?",
	"Əgər farted və başqa kimsə ittiham mi?"Əgər sizin tər cəhd mi?",
	"Bu otaqda kim bu gün üçün ən pis adam olacaq? Niyə?",
	"Əgər yenidən doğulsaydın, hansı əsrdə doğulmaq istəyirsən?"Əgər söylədiyiniz və ya etdiyiniz şeyi silmək üçün vaxtında geri dönə bilsəydiniz, hansı il olardı?",
	"Sevgiliniz və ya qızınız bir dəfə sizi qarışdırdı?", "Əgər birdən-birə görünməz olsaydı nə edərdiniz?",
	"Banyoda qaldığınız ən uzun vaxt nədir və niyə belə uzun müddət qaldınız?"Mənə heç gördüyüm ən qəribə yuxu haqqında danışın.",
	"Sən qəlbində yazırsan?", "Siz hələ nə ən Uşaq şey nədir?", "Hansı Uşaq filmini təkrar-təkrar izləyə bilərsiniz?",
	"Ayağınızın pis qoxusu varmı?", "Siz gülünc ləqəb var?", "Telefonunuzda ən çox vaxtınızı hansı tətbiqdə sərf edirsiniz?",
	"Bir oturuşda yediyiniz ən böyük yemək nədir?", "Bir rəqs edirsiniz?", "Sən qaranlıqdan qorxursan?",
	"Bütün gün evdə olsaydı nə edərdiniz?"Gündə neçə öz-özünə işləyən çəkirsiniz?"Son dəfə dişlərinizi fırçaladığınız zaman?",
	"Sevdiyiniz pijama necə görünür?", "Əgər yerdən bir şey yeyilmiş mi?"Nə etməli olmadığın bir şey etdiyiniz zaman tutuldun?",
	"Bədəninizin hansı hissəsini sevirsiniz, hansı hissəni nifrət edirsiniz?", "Siz heç biti var?",
	"Əgər sizin şalvar biçmək mi?", "Siz boşqab yalama edirsiniz?", "Heç kim sənin haqqında bir şey bilmir?",
	"Sən nə vaxtsa öz boşqabını yandırıbsan?"Dirsək yalama edə bilərəmmi?"Burada hər kəsin yanan binadan qurtarmağa çalışırsan və kimsə tərk etməlisən, kimdən ayrılacaqsan?",
	"Telefon zəng etdiyiniz son şey nə idi?", "Sizin telefon app aradan qaldırılması idi, əgər siz silindi nə olardı?"Əlaqələrinizdə ən böyük qorxunuz nədir?",
	"Otaqda hər bir şəxs haqqında bir müsbət və bir mənfi şey söyləyin.", "Siz kimi deyil ki, pis vərdişləri var?",
	"Həyatınızda heç etdiyiniz ən çılpaq şey nədir?"Əgər adada üç gün sıxışmış olsaydınız, bu qrupdan kim seçərdiniz?",
	"Bu otaqda ən zəhlətökən adam kimdir?"Əgər bu qrupdan birinə evlənmək məcburiyyətində olsaydınız, kim olardı?", "Sizin ən uzun əlaqələr nə qədər davam etdi?",
	"Əgər ünlü sənə İnstagram' da tabe olsaydı, bu məşhurluğun kim olmasını istərdin?", "Əgər İnstagram' dakı Beşləri aradan qaldırmaq məcburiyyətində olsaydınız, kimdən çıxardınız?",
	"Neçə uşaq sahibi olmaq istəyirsən?", "Sizin xəyalları insan təsvir.", "Messi və ya Ronaldo?","Təslim olmaq və ya Fıfa?",
	"İlk işiniz nə idi?"Universitet qarşısında ən böyük qorxu nədir?"Ən yaxşı dostunuzun sənin kimi eyni kollecə daxil olmasını istəyirsinizmi?",
	"İndiki sevgilinizin və ya qızınızın eyni kollecdə olmasını istəyirsinizmi?", "Sizin xəyalları iş və nə?",
	"Siz dərs uğursuz mi?", "Siz heç bir hilekarlık var?", "Əgər sinif yuxuda mi?"Kim heç vaxt sinifdə yanınızda oturmaq istəmirsiniz?",
	"Sən nə vaxtsa dərslərə gecikmisən?", "Siz heç müəllim qarşısında nə ən utandırıcı nədir?"Sən nə vaxtsa saqqızı masanın altına atmısan?",
	"Əgər məktəbdə mübahisə etdiniz mi?", "Nə heç imtahan qəbul etdiyiniz ən pis bal idi?"Sinifdə yuxuya düşdünüzmü?"Səni nə vaxtsa yaxalayıblar?",
